language: php
sudo: false
dist: trusty
cache:
    pip: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - TARGET=test

matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

          # Coverage
        - php: 7.1
          env:
            - PHPUNIT_FLAGS="-v --coverage-clover build/logs/clover.xml"
            - SYMFONY_PHPUNIT_VERSION="6.5"
            - COVERAGE=true

          # Test LTS versions. This makes sure we do not use Symfony packages with version greater
          # than 2 or 3 respectively. Read more at https://github.com/symfony/lts
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^2"

        - php: 7.2
          env: DEPENDENCIES="symfony/lts:^3"

          #doc
        - php: 7.2
          env: TARGET=docs

        - php: 7.2
          env: STABILITY="dev"

        - php: 7.2
          env: TARGET=phpstan LEVEL=0

        - php: 7.2
          env: TARGET=phpstan LEVEL=8

    allow_failures:
        - env: STABILITY="dev"
        - env: TARGET=phpstan LEVEL=8

before_install:
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;

script:
    - if [ -x .travis/script_${TARGET}.sh ]; then .travis/script_${TARGET}.sh; fi;

after_success: .travis/success.sh

branches:
    only: master
