language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - SYMFONY_VERSION=2.3.*

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

matrix:
    include:
        - php: 5.6
          services: [docker]
          env: DOCKER_BUILD=true
        - php: 5.6
          env: SYMFONY_VERSION=2.2.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.1.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.2.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*@dev SYMFONY_DEPRECATIONS_HELPER=strict
    allow_failures:
        - env: SYMFONY_VERSION=3.3.*@dev SYMFONY_DEPRECATIONS_HELPER=strict

notifications:
    email: geloen.eric@gmail.com
