language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

dist: trusty

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=2.7.*

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

matrix:
    include:
        - php: 5.6
          services: [docker]
          env: DOCKER_BUILD=true
        - php: 5.6
          env: SYMFONY_VERSION=2.7.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 5.6
          env: SYMFONY_VERSION=3.2.*
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*@dev
    allow_failures:
        - env: SYMFONY_VERSION=3.3.*@dev

notifications:
    email: geloen.eric@gmail.com
